log_level: INFO

root_note: 60

laser_array:
  size: 2 # number of lasers
  translation_table: [12, 11] # mapping from note to laser index

ipc:
  port: /dev/ttyS0
  baudrate: 1152000

  cables:
    din: 0
    usb: 1
    ble: 2
    laser_array: 3

camera:
  # mechanical parameters
  fov: [53.50, 41.41] # field of view in degrees
  mount_angle: 20.0 # angle between camera center and vertical axis in degrees
  mount_distance: 0.135 # distance from camera to laser plane in meters

  # basic confguration
  resolution: [640, 480] # VGA resolution
  framerate: 60 # max: 90
  rotation: 180 # configure any 90 degree rotation

  # exposure settings
  shutter_speed: 5000 # in microseconds
  iso: 10

  # image settings
  brightness: 50
  contrast: 0
  saturation: 0
  sharpness: 0

# settings during the calibration process
image_calibrator:
  preblur: 17 # gaussian blur kernel size
  threshold: 0.4 # minimum brightness to be considered a beam

# settings during normal operation
image_processor:
  preblur: 23 # gaussian blur kernel size

  threshold: 10 # minimum brightness to be considered a beam (0-255)
  length_min: 0.05 # minimum beam length in meters
  length_max: 2.0 # maximum beam length in meters

  filter_cutoff: 6 # cutoff frequency in Hz
  filter_size: 23 # filter kernel size

  modulation_gain: 15 # vibrato factor before soft-clipping (e. g. "drive")
