num_lasers: 2
laser_translation_table: [11, 12]

root_note: 60

camera:
  # mechanical parameters
  fov: [53.50, 41.41] # field of view in degrees
  mount_angle: 20.0 # angle between camera center and vertical axis in degrees
  mount_distance: 0.135 # distance from camera to laser plane in meters

  # basic confguration
  resolution: [640, 480] # VGA resolution
  framerate: 60
  rotation: 180 # configure any 90 degree rotation

  # exposure settings
  shutter_speed: 5000 # in microseconds
  iso: 10

  # image settings
  brightness: 50
  contrast: 0
  saturation: 0
  sharpness: 0

# settings during the calibration process
image_calibrator:
  preblur: 17 # gaussian blur kernel size
  threshold: 0.4 # minimum brightness to be considered a beam

# settings during normal operation
image_processor:
  preblur: 23 # gaussian blur kernel size
  threshold: 0.04 # minimum brightness to be considered a beam
  beam_length_max: 2.0 # maximum beam length in meters
