log_level: INFO

root_note: 60

save_debug_images: true

laser_array:
  size: 15 # number of lasers
  translation_table: [4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19] # mapping from note to laser index

ipc:
  port: /dev/ttyAMA0
  baudrate: 115200

din_midi:
  port: /dev/ttyAMA2
  baudrate: 38400 # note: this results in 31250 baud when using "dtoverlay=midi-uart2" in /boot/config.txt

camera:
  # mechanical parameters
  fov: [53.50, 41.41] # field of view in degrees
  mount_angle: 15.0 # angle between camera center and vertical axis in degrees
  mount_distance: 0.14338 # distance from camera to laser plane in meters

  # basic confguration
  resolution: [640, 480] # VGA resolution
  framerate: 30 # max: 50
  rotation: 180 # configure any 90 degree rotation

  # exposure settings
  shutter_speed: 10000 # in microseconds
  iso: 20

  # image settings
  brightness: 50
  contrast: 0
  saturation: 0
  sharpness: 0

# settings during the calibration process
image_calibrator:
  calibration_file: calibration.yaml # path to the calibration file

  preblur: 3 # gaussian blur kernel size
  threshold: 50 # minimum brightness to be considered
  min_coverage: 0.4 # percentual number of blobs that must be captured for each beam

# settings during normal operation
image_processor:
  preblur: 1 # gaussian blur kernel size

  threshold: 60 # minimum brightness to be considered a beam (0-255)
  length_min: 0.05 # minimum beam length in meters
  length_max: 2.0 # maximum beam length in meters

  filter_cutoff: 6 # cutoff frequency in Hz
  filter_size: 3 # filter kernel size

  modulation_gain: 15 # vibrato factor before soft-clipping (e. g. "drive")
