M48
; DRILL file {KiCad 8.0.4} date 2024-08-25T15:35:27+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-25T15:35:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X4.8862Y-4.5235
X5.1138Y-4.5235
T2
X3.18Y-2.53
X3.18Y-4.62
X5.2Y-4.08
X6.82Y-2.53
M30
