app:
  log_level: INFO # DEBUG, INFO, WARNING, ERROR

  save_debug_images: false # save camera visualization images when calibrating
  generate_debug_intersections: true # generate random intersections when the camera is disabled

  send_standby: true # enable STM board standby mode when the application is stopped

laser_array:
  size: 11 # number of lasers
  translation_table: [6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17] # mapping from note to laser index

ipc:
  # How to enable the primary UART:
  # - run raspi-config
  # - go to "Interfacing Options" > "Serial"
  # - disable the login shell over serial
  # - enable the serial port hardware
  # - reboot

  # # for Raspberry Pi 5:
  port: /dev/ttyAMA0
  baudrate: 115200

  # for Raspberry Pi 3 Model B+:
  # port: /dev/serial1 # Mini UART
  # baudrate: 115200

din_midi:
  # for Raspberry Pi 5:
  # Add to /boot/firmware/config.txt:
  # dtoverlay=uart2-pi5 # enable the second UART
  # dtoverlay=midi-uart2-pi5 # configure clock rate for MIDI
  port: /dev/ttyAMA2
  baudrate: 38400 # note: this results in 31250 baud when using "dtoverlay=midi-uart2" in /boot/config.txt

  # for Raspberry Pi 3 Model B+:
  # # Add to /boot/config.txt:
  # # dtoverlay=disable-bt
  # # enable_uart=1
  # # dtoverlay=uart1,txd1_pin=32,rxd1_pin=33
  # # dtoverlay=midi-uart0
  # port: /dev/serial0 # PL011 UART
  # baudrate: 38400

camera:
  # mechanical parameters
  fov: [130, 100]  # # field of view in degrees (for Raspi Camera v1:  [53.50, 41.41], for Raspi Camera v1 with Fisheye lens: [130, 100])
  mount_angle: 20 # angle between camera center and vertical axis in degrees (15 degrees for Raspi Camera v1, should be changed to 20 degrees with Fisheye lens)
  mount_distance: 0.14338 # distance from camera to laser plane in meters

  # basic confguration
  resolution: [640, 480] # VGA resolution
  stream_resolution: [640, 480] # VGA resolution
  framerate: 50 # max: 50
  rotation: 180 # configure any 90 degree rotation

  # exposure settings
  # shutter_speed: 200000 # in microseconds
  # iso: 1000

  # image settings
  # brightness: 50
  # contrast: 0
  # saturation: 0
  # sharpness: 0

  settings:
    # exposure settings
    shutter_speed:
      type: int
      range: [100, 20000] # in microseconds
      default: 10000 # in microseconds
    iso:
      type: int
      range: [100, 1600] # ISO range
      default: 200 # ISO value

# settings during the calibration process
image_calibrator:
  settings:
    calibration_data:
      type: str
      default: "{}"
      client_writable: false

  preblur: 3 # gaussian blur kernel size
  threshold: 150 # minimum brightness to be considered
  min_coverage: 0.2 # percentual number of blobs that must be captured for each beam

# settings during normal operation
image_processor:
  preblur: 1 # gaussian blur kernel size

  threshold: 128 # minimum brightness to be considered a beam (0-255)
  length_min: 0.05 # minimum beam length in meters
  length_max: 2 # maximum beam length in meters

  filter_cutoff: 6 # cutoff frequency in Hz
  filter_size: 3 # filter kernel size

  modulation_gain: 15 # vibrato factor before soft-clipping (e. g. "drive")

orchestrator:
  settings:
    flipped:
      type: bool
      default: false

    unplucked_beam_brightness:
      type: int
      range: [0, 127]
      default: 32
    plucked_beam_brightness:
      type: int
      range: [0, 127]
      default: 127

    key:
      type: int
      range: [0, 11]
      default: 0
    octave:
      type: int
      range: [0, 10]
      default: 4
    mode:
      type: int
      range: [0, 6]
      default: 0

hwbutton:
  settings:
    sequence_sxx:
      type: str
      default: "flip"
      client_writable: true

    sequence_ssx:
      type: str
      default: "calibrate"
      client_writable: true

    sequence_sss:
      type: str
      default: "none"
      client_writable: true

    sequence_lxx:
      type: str
      default: "poweroff"
      client_writable: true

    sequence_slx:
      type: str
      default: "none"
      client_writable: true

    sequence_ssl:
      type: str
      default: "none"
      client_writable: true

  available_actions:
    - none
    - poweroff
    - calibrate
    - flip
