name: Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Python Code using Black and Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      # - name: Run black
      #   working-directory: .
      #   run: black --check $(git ls-files '*.py')

      # - name: Run pylint
      #   working-directory: .
      #   run: pylint $(git ls-files '*.py')

  test:
    name: Test Python Code using Unittest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install numpy opencv-python
          pip install -r requirements.txt

      - name: Run tests
        working-directory: .
        run: python -m unittest discover -v -s tests -p "test_*.py" -t .
