name: STM32 Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # lint:
  #   name: Lint STM32 Firmware using Clang-Format
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Clang-Format
  #       uses: ilgarm/gha:clang-format-13

  #     - name: Run clang-format
  #       working-directory: ./stm
  #       run: clang-format --dry-run --Werror $(git ls-files 'Core' 'Drivers/Laser_Array' 'Drivers/Midi')

  build:
    name: Build STM32 Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup arm-none-eabi-gcc
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: 11.3.1

      - name: Build firmware
        working-directory: ./stm
        run: make
